import { useMemo, useState } from 'react';
import { outreachApi } from '../api';
import type { ConnectionInfo, Workspace } from '../types';
import {
  createWorkspaceId,
  isAppsScriptExecUrl,
  maskToken,
} from '../utils';

type SetupWizardProps = {
  initialWorkspace?: Workspace | null;
  canCancel: boolean;
  onCancel: () => void;
  onSave: (
    workspace: Workspace,
    remember: boolean,
    info: ConnectionInfo,
  ) => void;
};

const steps = [
  'Create spreadsheet',
  'Install backend',
  'Initialise and get token',
  'Deploy web app',
  'Connect workspace',
];

const helpLinks = {
  createSheet: 'https://sheets.new',
  boundScript: 'https://developers.google.com/apps-script/guides/bound',
  logging: 'https://developers.google.com/apps-script/guides/logging',
  webApps: 'https://developers.google.com/apps-script/guides/web',
};

export function SetupWizard({
  initialWorkspace,
  canCancel,
  onCancel,
  onSave,
}: SetupWizardProps) {
  const [step, setStep] = useState(initialWorkspace ? 4 : 0);
  const [label, setLabel] = useState(initialWorkspace?.label ?? '');
  const [apiUrl, setApiUrl] = useState(initialWorkspace?.apiUrl ?? '');
  const [apiToken, setApiToken] = useState(
    initialWorkspace?.apiToken ?? '',
  );
  const [remember, setRemember] = useState(true);
  const [showToken, setShowToken] = useState(false);
  const [busy, setBusy] = useState(false);
  const [copyMessage, setCopyMessage] = useState('');
  const [error, setError] = useState('');
  const [tested, setTested] = useState<ConnectionInfo | null>(null);

  const draftWorkspace = useMemo<Workspace>(
    () => ({
      id: initialWorkspace?.id ?? createWorkspaceId(),
      label: label.trim() || tested?.spreadsheet.name || 'My workspace',
      apiUrl: apiUrl.trim(),
      apiToken: apiToken.trim(),
    }),
    [apiToken, apiUrl, initialWorkspace?.id, label, tested?.spreadsheet.name],
  );

  async function copySetupFile(path: string, friendlyName: string) {
    setError('');
    setCopyMessage('');

    try {
      const response = await fetch(
        `${import.meta.env.BASE_URL}setup/${path}`,
      );
      if (!response.ok) throw new Error(`Could not load ${friendlyName}.`);
      await navigator.clipboard.writeText(await response.text());
      setCopyMessage(`${friendlyName} copied to the clipboard.`);
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : `Could not copy ${friendlyName}.`,
      );
    }
  }

  async function testConnection() {
    setError('');
    setTested(null);

    if (!isAppsScriptExecUrl(apiUrl)) {
      setError(
        'Paste the deployed Google Apps Script URL ending in /exec. Editor and /dev URLs do not work here.',
      );
      return;
    }

    if (!apiToken.trim()) {
      setError('Paste the API token generated by generateApiToken().');
      return;
    }

    setBusy(true);
    try {
      const info = await outreachApi.connectionInfo(draftWorkspace);
      setTested(info);
      if (!label.trim()) setLabel(info.spreadsheet.name);
    } catch (caught) {
      setError(
        caught instanceof Error
          ? caught.message
          : 'The connection test failed.',
      );
    } finally {
      setBusy(false);
    }
  }

  function saveWorkspace() {
    if (!tested) {
      setError('Test the connection successfully before saving it.');
      return;
    }
    onSave(draftWorkspace, remember, tested);
  }

  return (
    <main className="setup-page">
      <div className="setup-shell">
        <aside className="setup-sidebar">
          <div>
            <p className="eyebrow">Workspace setup</p>
            <h1>Connect Outreach Desk</h1>
            <p>
              Each person can connect this static app to a different Google
              Spreadsheet. The sheet remains private; Apps Script provides the
              small API used by the app.
            </p>
          </div>

          <ol className="setup-progress">
            {steps.map((item, index) => (
              <li
                key={item}
                className={
                  index === step
                    ? 'current'
                    : index < step
                      ? 'complete'
                      : ''
                }
              >
                <button onClick={() => setStep(index)}>
                  <span>{index < step ? '✓' : index + 1}</span>
                  {item}
                </button>
              </li>
            ))}
          </ol>

          <div className="setup-security-note">
            <strong>Where credentials are stored</strong>
            <p>
              Remembered workspaces are saved in this browser&apos;s localStorage.
              Temporary workspaces use sessionStorage and disappear when the
              browser session ends. Nothing is committed to GitHub.
            </p>
          </div>
        </aside>

        <section className="setup-content">
          <div className="setup-content-header">
            <div>
              <p className="eyebrow">
                Step {step + 1} of {steps.length}
              </p>
              <h2>{steps[step]}</h2>
            </div>
            {canCancel && (
              <button className="button button-secondary" onClick={onCancel}>
                Cancel
              </button>
            )}
          </div>

          {(copyMessage || error) && (
            <div
              className={`inline-message ${error ? 'inline-error' : ''}`}
              role="status"
            >
              {error || copyMessage}
            </div>
          )}

          {step === 0 && (
            <div className="setup-step">
              <p className="setup-lead">
                Start with an empty Google Spreadsheet. You do not need to
                publish it or share it publicly.
              </p>
              <div className="setup-action-card">
                <h3>Create the spreadsheet</h3>
                <p>
                  Open a new sheet, give it a useful name, then use
                  <strong> Extensions → Apps Script</strong> from that sheet.
                </p>
                <div className="setup-button-row">
                  <a
                    className="button button-primary"
                    href={helpLinks.createSheet}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Create a new Google Sheet
                  </a>
                  <a
                    className="button button-secondary"
                    href={helpLinks.boundScript}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Google&apos;s bound-script guide
                  </a>
                </div>
              </div>
              <div className="setup-tip">
                <strong>Already completed the Google setup?</strong>
                <button className="text-button" onClick={() => setStep(4)}>
                  Skip directly to the connection form
                </button>
              </div>
            </div>
          )}

          {step === 1 && (
            <div className="setup-step">
              <p className="setup-lead">
                The Apps Script backend creates and maintains the
                <code> Venues</code>, <code>Imports</code> and
                <code> Settings</code> sheets.
              </p>

              <div className="numbered-instructions">
                <article>
                  <span>1</span>
                  <div>
                    <h3>Open Apps Script</h3>
                    <p>
                      In your spreadsheet select <strong>Extensions → Apps
                      Script</strong>.
                    </p>
                  </div>
                </article>
                <article>
                  <span>2</span>
                  <div>
                    <h3>Replace Code.gs</h3>
                    <p>
                      Delete the sample function, copy the supplied backend and
                      paste it into <code>Code.gs</code>.
                    </p>
                    <div className="setup-button-row">
                      <button
                        className="button button-primary"
                        onClick={() =>
                          void copySetupFile('Code.gs.txt', 'Code.gs')
                        }
                      >
                        Copy Code.gs
                      </button>
                      <a
                        className="button button-secondary"
                        href={`${import.meta.env.BASE_URL}setup/Code.gs.txt`}
                        download="Code.gs"
                      >
                        Download Code.gs
                      </a>
                    </div>
                  </div>
                </article>
                <article>
                  <span>3</span>
                  <div>
                    <h3>Save the project</h3>
                    <p>
                      The default manifest is sufficient. An optional manifest
                      is included for people who prefer explicit OAuth scopes.
                    </p>
                    <div className="setup-button-row">
                      <button
                        className="button button-secondary"
                        onClick={() =>
                          void copySetupFile(
                            'appsscript.json',
                            'appsscript.json',
                          )
                        }
                      >
                        Copy optional manifest
                      </button>
                    </div>
                  </div>
                </article>
              </div>
            </div>
          )}

          {step === 2 && (
            <div className="setup-step">
              <p className="setup-lead">
                Run two functions from the Apps Script editor. Google will ask
                you to authorise access to this spreadsheet and external URLs.
              </p>
              <div className="numbered-instructions">
                <article>
                  <span>1</span>
                  <div>
                    <h3>Run setupProject</h3>
                    <p>
                      Choose <code>setupProject</code> from the function menu and
                      press <strong>Run</strong>. This creates the sheet tabs and
                      records the spreadsheet ID.
                    </p>
                  </div>
                </article>
                <article>
                  <span>2</span>
                  <div>
                    <h3>Run generateApiToken</h3>
                    <p>
                      Choose <code>generateApiToken</code> and run it. Running it
                      again later replaces and invalidates the old token.
                    </p>
                  </div>
                </article>
                <article>
                  <span>3</span>
                  <div>
                    <h3>Copy the token</h3>
                    <p>
                      Open <strong>Execution log</strong> at the bottom of the
                      editor and copy the long value after “API token”.
                    </p>
                    <a
                      href={helpLinks.logging}
                      target="_blank"
                      rel="noreferrer"
                    >
                      Google&apos;s Apps Script logging guide
                    </a>
                  </div>
                </article>
              </div>
              <div className="setup-warning">
                Treat the token like a password. Do not put it in a committed
                <code> .env</code> file or paste it into a public issue.
              </div>
            </div>
          )}

          {step === 3 && (
            <div className="setup-step">
              <p className="setup-lead">
                Deploy the script as a web app so this browser can call it.
              </p>
              <div className="numbered-instructions">
                <article>
                  <span>1</span>
                  <div>
                    <h3>Create a deployment</h3>
                    <p>
                      In Apps Script choose <strong>Deploy → New deployment</strong>
                      and select <strong>Web app</strong>.
                    </p>
                  </div>
                </article>
                <article>
                  <span>2</span>
                  <div>
                    <h3>Choose access settings</h3>
                    <p>
                      Set <strong>Execute as: Me</strong>. For a static frontend,
                      choose the option that permits access without an
                      interactive Google sign-in—normally <strong>Anyone</strong>.
                      The API token still protects every data request.
                    </p>
                  </div>
                </article>
                <article>
                  <span>3</span>
                  <div>
                    <h3>Copy the /exec URL</h3>
                    <p>
                      Copy the deployed web-app URL. It must end in
                      <code> /exec</code>. Do not use the editor URL or the test
                      deployment ending in <code>/dev</code>.
                    </p>
                    <a
                      href={helpLinks.webApps}
                      target="_blank"
                      rel="noreferrer"
                    >
                      Google&apos;s web-app deployment guide
                    </a>
                  </div>
                </article>
              </div>
              <div className="setup-warning">
                Some managed Google Workspace accounts disable public web-app
                deployments. In that case an administrator must allow it, or
                you need to use a personal Google account for this version.
              </div>
            </div>
          )}

          {step === 4 && (
            <div className="setup-step">
              <p className="setup-lead">
                Paste the deployment details, test them, and save this workspace
                in the browser.
              </p>

              <div className="connection-form">
                <label>
                  Workspace name
                  <input
                    value={label}
                    onChange={(event) => setLabel(event.target.value)}
                    placeholder="Italian venues"
                  />
                  <small>
                    This is only a local label used by the workspace switcher.
                  </small>
                </label>

                <label>
                  Apps Script web-app URL
                  <input
                    value={apiUrl}
                    onChange={(event) => {
                      setApiUrl(event.target.value);
                      setTested(null);
                    }}
                    placeholder="https://script.google.com/macros/s/.../exec"
                    inputMode="url"
                  />
                  <small>
                    Find it under Apps Script → Deploy → Manage deployments.
                  </small>
                </label>

                <label>
                  API token
                  <div className="secret-input">
                    <input
                      type={showToken ? 'text' : 'password'}
                      value={apiToken}
                      onChange={(event) => {
                        setApiToken(event.target.value);
                        setTested(null);
                      }}
                      placeholder="Paste the token from the execution log"
                      autoComplete="off"
                    />
                    <button
                      type="button"
                      onClick={() => setShowToken((current) => !current)}
                    >
                      {showToken ? 'Hide' : 'Show'}
                    </button>
                  </div>
                  <small>
                    Current value: {maskToken(apiToken)}. It is sent only to your
                    Apps Script endpoint over HTTPS.
                  </small>
                </label>

                <label className="remember-choice">
                  <input
                    type="checkbox"
                    checked={remember}
                    onChange={(event) => setRemember(event.target.checked)}
                  />
                  <span>
                    <strong>Remember this workspace on this device</strong>
                    <small>
                      Uncheck on a shared computer. The connection will then last
                      only for the current browser session.
                    </small>
                  </span>
                </label>
              </div>

              <div className="setup-button-row">
                <button
                  className="button button-secondary"
                  onClick={() => void testConnection()}
                  disabled={busy}
                >
                  {busy ? 'Testing…' : 'Test connection'}
                </button>
                <button
                  className="button button-primary"
                  onClick={saveWorkspace}
                  disabled={!tested || busy}
                >
                  Save and continue
                </button>
              </div>

              {tested && (
                <div className="connection-success">
                  <div>
                    <span>✓</span>
                    <div>
                      <strong>Connected successfully</strong>
                      <p>
                        {tested.spreadsheet.name} ·{' '}
                        {tested.spreadsheet.venueCount} records ·{' '}
                        {tested.spreadsheet.importCount} imports
                      </p>
                    </div>
                  </div>
                  <a
                    href={tested.spreadsheet.url}
                    target="_blank"
                    rel="noreferrer"
                  >
                    Open spreadsheet
                  </a>
                </div>
              )}
            </div>
          )}

          <div className="setup-navigation">
            <button
              className="button button-secondary"
              onClick={() => setStep((current) => Math.max(0, current - 1))}
              disabled={step === 0}
            >
              Previous
            </button>
            {step < steps.length - 1 && (
              <button
                className="button button-primary"
                onClick={() =>
                  setStep((current) => Math.min(steps.length - 1, current + 1))
                }
              >
                Next
              </button>
            )}
          </div>
        </section>
      </div>
    </main>
  );
}
